image: ghcr.io/cirruslabs/flutter:stable

tasks:
  - name: Flutter Web Dev
    init: |
      flutter config --enable-web
      flutter pub get
    command: |
      flutter run -d web-server --web-port=4000 --web-hostname=0.0.0.0

ports:
  - port: 4000
    onOpen: open-preview
    visibility: public

vscode:
  extensions:
    - Dart-Code.dart-code
    - Dart-Code.flutter
