include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - audit_microia/**
    - backups/**
    - build/**
    - build_logs/**
    - dev/archive/**
    - .dart_tool/**
    - ios/**
    - android/**
    - macos/**
    - windows/**
    - linux/**

linter:
  rules: {}
