name: presto_app
description: Prest'o app
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  crypto: ^3.0.6
  firebase_auth: ^6.1.0
  sign_in_with_apple: ^7.0.1
  http: ^1.2.2 
  

  cupertino_icons: ^1.0.8

  # 🔥 Firebase / Firestore / URL launcher
  firebase_core: ^4.3.0
  firebase_analytics: ^12.0.1
  firebase_crashlytics: ^5.0.0
  auto_size_text: ^3.0.0
  cloud_firestore: ^6.3.0
  cloud_functions: ^6.0.5
  url_launcher: ^6.3.0
  image_picker: ^1.2.2
  firebase_storage: ^13.3.0
  firebase_messaging: ^16.1.0
  firebase_performance: ^0.11.0+1
  firebase_remote_config: ^6.1.1
  flutter_local_notifications: ^19.4.0
  firebase_app_check: ^0.4.1+3
  recaptcha_enterprise_flutter: ^18.8.2
  record: ^6.1.2
  path_provider: ^2.1.0
  google_mobile_ads: ^7.0.0
  flutter_slidable: ^3.1.2
  file_picker: 8.3.7
  font_awesome_flutter: ^11.0.0
  flutter_svg: ^2.0.9
  shared_preferences: ^2.5.3
  web: ^1.0.0
  cross_file: ^0.3.4+2
  firebase_ai: ^3.11.0
  google_sign_in: ^7.2.0
  video_player: ^2.9.2
  just_audio: ^0.10.5
  audioplayers: ^6.7.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  firebase_core_platform_interface: ^6.0.3
  flutter_lints: ^6.0.0

flutter:
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter-Black.ttf
          weight: 900
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/logowebp.webp
    - assets/data/cities/
    - assets/data/cities_compact.json
    - assets/carousel_home/
