"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.LISTING_VALIDATION = exports.EMAIL_RETRY_MINUTES = exports.COLLECTIONS = void 0;
exports.COLLECTIONS = {
    users: "users",
    profiles: "profiles",
    userProfiles: "user_profiles",
    offers: "offers",
    listings: "listings",
    listingDraftsV2: "listingDrafts",
    listingModeration: "listingModeration",
    listingReports: "listingReports",
    chatThreads: "chatThreads",
    adminActions: "adminActions",
    categories: "categories",
    cities: "cities",
    analyticsSnapshots: "analyticsSnapshots",
    appConfig: "appConfig",
    newsletterCampaigns: "newsletter_campaigns",
    listingDrafts: "listing_drafts",
    conversations: "conversations",
    conversationMessages: "conversation_messages",
    savedSearches: "saved_searches",
    favorites: "favorites",
    supportTickets: "support_tickets",
    reports: "reports",
    subscriptions: "subscriptions",
    billingInvoices: "billing_invoices",
    notifications: "notifications",
    notificationPreferences: "notification_preferences",
    pushTokens: "push_tokens",
    emailTemplates: "email_templates",
    emailTemplateVersions: "email_template_versions",
    emailEvents: "email_events",
    emailJobs: "email_jobs",
    emailLogs: "email_logs",
    emailSuppressions: "email_suppressions",
    emailBounces: "email_bounces",
    emailUnsubscribes: "email_unsubscribes",
    emailProviderWebhooks: "email_provider_webhooks",
    audits: "audits",
    systemSettings: "system_settings",
};
exports.EMAIL_RETRY_MINUTES = [1, 5, 20, 120, 480];
exports.LISTING_VALIDATION = {
    titleMinLength: 10,
    titleMaxLength: 120,
    descriptionMinLength: 30,
    descriptionMaxLength: 4000,
    maxMediaCount: 10,
};
//# sourceMappingURL=constants.js.map