org.gradle.daemon=false
org.gradle.parallel=false
org.gradle.configureondemand=false
org.gradle.workers.max=1
org.gradle.jvmargs=-Xmx6144m -XX:MaxMetaspaceSize=1024m -XX:ReservedCodeCacheSize=512m -XX:+UseG1GC -Dfile.encoding=UTF-8
android.useAndroidX=true
android.enableJetifier=true
android.newDsl=false
android.builtInKotlin=false
