export const COLLECTIONS = {
  users: "users",
  userProfiles: "user_profiles",
  listings: "listings",
  listingDrafts: "listing_drafts",
  conversations: "conversations",
  conversationMessages: "conversation_messages",
  savedSearches: "saved_searches",
  favorites: "favorites",
  supportTickets: "support_tickets",
  reports: "reports",
  subscriptions: "subscriptions",
  billingInvoices: "billing_invoices",
  notificationPreferences: "notification_preferences",
  emailTemplates: "email_templates",
  emailTemplateVersions: "email_template_versions",
  emailEvents: "email_events",
  emailJobs: "email_jobs",
  emailLogs: "email_logs",
  emailSuppressions: "email_suppressions",
  emailBounces: "email_bounces",
  emailUnsubscribes: "email_unsubscribes",
  emailProviderWebhooks: "email_provider_webhooks",
  audits: "audits",
  systemSettings: "system_settings",
} as const;

export const EMAIL_RETRY_MINUTES = [1, 5, 20, 120, 480];
