import { defineTemplate, buildEmailHtml, buildEmailText } from "./shared";

export const forgotPasswordTemplate = defineTemplate({
  id: "forgot_password",
  templateCode: "tpl_transactional_account_password_forgotten_v2",
  category: "security",
  type: "transactional",
  tone: "security",
  goal: "Permettre la reinitialisation securisee du mot de passe.",
  event: "user.password_reset.requested",
  variables: [
    { key: "firstName", type: "string", required: true, description: "Prenom du destinataire" },
    { key: "resetUrl", type: "url", required: true, description: "Lien de reinitialisation signe" },
    { key: "expiresInMinutes", type: "number", required: false, description: "Duree de validite du lien" },
    { key: "helpUrl", type: "url", required: false, description: "Lien support" },
  ],
  subject: "Reinitialisez votre mot de passe",
  previewText: "Utilisez ce lien securise pour definir un nouveau mot de passe.",
  cta: { label: "Reinitialiser mon mot de passe", urlVariable: "resetUrl" },
  secondaryCta: { label: "Besoin d aide", urlVariable: "helpUrl", secondary: true },
  html: buildEmailHtml({
    title: "Reinitialisez votre mot de passe",
    previewText: "Utilisez ce lien securise pour definir un nouveau mot de passe.",
    intro: "Bonjour {{firstName}},",
    body: [
      "Nous avons recu une demande de reinitialisation de mot de passe pour votre compte e-livre resto.",
      "Le lien ci-dessous est personnel et expire dans {{expiresInMinutes}} minutes.",
      "Si vous n etes pas a l origine de cette demande, vous pouvez ignorer cet email.",
    ],
    ctaLabel: "Reinitialiser mon mot de passe",
    ctaVariable: "resetUrl",
    secondaryLabel: "Contacter le support",
    secondaryVariable: "helpUrl",
    tone: "security",
    type: "transactional",
  }),
  text: buildEmailText({
    title: "Reinitialisez votre mot de passe",
    previewText: "Utilisez ce lien securise pour definir un nouveau mot de passe.",
    intro: "Bonjour {{firstName}},",
    body: [
      "Nous avons recu une demande de reinitialisation de mot de passe.",
      "Le lien expire dans {{expiresInMinutes}} minutes.",
      "Si vous n etes pas a l origine de cette demande, ignorez cet email.",
    ],
    ctaLabel: "Reinitialiser mon mot de passe",
    ctaVariable: "resetUrl",
    secondaryLabel: "Contacter le support",
    secondaryVariable: "helpUrl",
  }),
  rules: {
    trigger: "user.password_reset.requested",
    sendWhen: "Quand l utilisateur demande un lien de reinitialisation.",
    skipWhen: ["Adresse email absente", "Compte introuvable"],
    unsubscribeAllowed: false,
    requiredPreferences: ["transactionalEmailEnabled"],
    idempotencyScope: "userId + reset request window",
  },
});