"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.processScheduledEmailDigests = exports.processEmailJobTrigger = exports.enqueueEmailJobsFromEventTrigger = exports.onBillingInvoiceUpdated = exports.onSubscriptionUpdated = exports.onReportUpdated = exports.onReportCreated = exports.onSupportTicketReplied = exports.onSupportTicketCreated = exports.onNotificationUpdated = exports.onNotificationCreated = exports.unregisterPushToken = exports.registerPushToken = exports.deleteConversationMessage = exports.deleteConversation = exports.unblockConversation = exports.blockConversation = exports.unarchiveConversation = exports.archiveConversation = exports.markConversationRead = exports.sendConversationMessage = exports.ensureOfferConversation = exports.enqueueUnreadMessageReminders = exports.onConversationSubMessageCreated = exports.onNewsletterCampaignUpdated = exports.onNewsletterCampaignCreated = exports.enqueueMarketingOnboardingEmails = exports.onLegalPrivacySettingsUpdated = exports.onLegalTermsSettingsUpdated = exports.expireOldListings = exports.notifyListingRejected = exports.notifyListingApproved = exports.logAdminAction = exports.applyUserRoleClaims = exports.sendChatMessage = exports.createChatThreadFromListing = exports.toggleFavorite = exports.reportListing = exports.processOfferPhoto = exports.incrementListingView = exports.submitListingDraft = exports.enqueueExpiringListingEmails = exports.onOfferUpdated = exports.onOfferCreated = exports.onListingPublished = exports.trackUserLogin = exports.reportPasswordChanged = exports.requestEmailVerificationEmail = exports.requestPasswordResetEmail = exports.onUserCreated = void 0;
exports.syncEmailAnalytics = exports.purgeOldEmailLogs = exports.purgeOldEmailWebhooks = exports.handleEmailProviderWebhook = exports.cleanupExpiredEmailJobs = exports.retryFailedEmailJobs = void 0;
const v2_1 = require("firebase-functions/v2");
const env_1 = require("./config/env");
(0, v2_1.setGlobalOptions)({
    secrets: env_1.EMAIL_PROVIDER_SECRETS,
});
var triggers_1 = require("./modules/auth/triggers");
Object.defineProperty(exports, "onUserCreated", { enumerable: true, get: function () { return triggers_1.onUserCreated; } });
var callables_1 = require("./modules/auth/callables");
Object.defineProperty(exports, "requestPasswordResetEmail", { enumerable: true, get: function () { return callables_1.requestPasswordResetEmail; } });
Object.defineProperty(exports, "requestEmailVerificationEmail", { enumerable: true, get: function () { return callables_1.requestEmailVerificationEmail; } });
Object.defineProperty(exports, "reportPasswordChanged", { enumerable: true, get: function () { return callables_1.reportPasswordChanged; } });
Object.defineProperty(exports, "trackUserLogin", { enumerable: true, get: function () { return callables_1.trackUserLogin; } });
var triggers_2 = require("./modules/listings/triggers");
Object.defineProperty(exports, "onListingPublished", { enumerable: true, get: function () { return triggers_2.onListingPublished; } });
Object.defineProperty(exports, "onOfferCreated", { enumerable: true, get: function () { return triggers_2.onOfferCreated; } });
Object.defineProperty(exports, "onOfferUpdated", { enumerable: true, get: function () { return triggers_2.onOfferUpdated; } });
var scheduled_1 = require("./modules/listings/scheduled");
Object.defineProperty(exports, "enqueueExpiringListingEmails", { enumerable: true, get: function () { return scheduled_1.enqueueExpiringListingEmails; } });
var listings_1 = require("./modules/marketplace/callables/listings");
Object.defineProperty(exports, "submitListingDraft", { enumerable: true, get: function () { return listings_1.submitListingDraft; } });
Object.defineProperty(exports, "incrementListingView", { enumerable: true, get: function () { return listings_1.incrementListingView; } });
var media_1 = require("./modules/marketplace/callables/media");
Object.defineProperty(exports, "processOfferPhoto", { enumerable: true, get: function () { return media_1.processOfferPhoto; } });
var reports_1 = require("./modules/marketplace/callables/reports");
Object.defineProperty(exports, "reportListing", { enumerable: true, get: function () { return reports_1.reportListing; } });
var favorites_1 = require("./modules/marketplace/callables/favorites");
Object.defineProperty(exports, "toggleFavorite", { enumerable: true, get: function () { return favorites_1.toggleFavorite; } });
var chat_1 = require("./modules/marketplace/callables/chat");
Object.defineProperty(exports, "createChatThreadFromListing", { enumerable: true, get: function () { return chat_1.createChatThreadFromListing; } });
Object.defineProperty(exports, "sendChatMessage", { enumerable: true, get: function () { return chat_1.sendChatMessage; } });
var admin_1 = require("./modules/marketplace/callables/admin");
Object.defineProperty(exports, "applyUserRoleClaims", { enumerable: true, get: function () { return admin_1.applyUserRoleClaims; } });
Object.defineProperty(exports, "logAdminAction", { enumerable: true, get: function () { return admin_1.logAdminAction; } });
var notifications_1 = require("./modules/marketplace/triggers/notifications");
Object.defineProperty(exports, "notifyListingApproved", { enumerable: true, get: function () { return notifications_1.notifyListingApproved; } });
Object.defineProperty(exports, "notifyListingRejected", { enumerable: true, get: function () { return notifications_1.notifyListingRejected; } });
var listings_2 = require("./modules/marketplace/scheduled/listings");
Object.defineProperty(exports, "expireOldListings", { enumerable: true, get: function () { return listings_2.expireOldListings; } });
var triggers_3 = require("./modules/legal/triggers");
Object.defineProperty(exports, "onLegalTermsSettingsUpdated", { enumerable: true, get: function () { return triggers_3.onLegalTermsSettingsUpdated; } });
Object.defineProperty(exports, "onLegalPrivacySettingsUpdated", { enumerable: true, get: function () { return triggers_3.onLegalPrivacySettingsUpdated; } });
var scheduled_2 = require("./modules/marketing/scheduled");
Object.defineProperty(exports, "enqueueMarketingOnboardingEmails", { enumerable: true, get: function () { return scheduled_2.enqueueMarketingOnboardingEmails; } });
var triggers_4 = require("./modules/marketing/triggers");
Object.defineProperty(exports, "onNewsletterCampaignCreated", { enumerable: true, get: function () { return triggers_4.onNewsletterCampaignCreated; } });
Object.defineProperty(exports, "onNewsletterCampaignUpdated", { enumerable: true, get: function () { return triggers_4.onNewsletterCampaignUpdated; } });
var triggers_5 = require("./modules/messaging/triggers");
Object.defineProperty(exports, "onConversationSubMessageCreated", { enumerable: true, get: function () { return triggers_5.onConversationSubMessageCreated; } });
var scheduled_3 = require("./modules/messaging/scheduled");
Object.defineProperty(exports, "enqueueUnreadMessageReminders", { enumerable: true, get: function () { return scheduled_3.enqueueUnreadMessageReminders; } });
var callables_2 = require("./modules/messaging/callables");
Object.defineProperty(exports, "ensureOfferConversation", { enumerable: true, get: function () { return callables_2.ensureOfferConversation; } });
Object.defineProperty(exports, "sendConversationMessage", { enumerable: true, get: function () { return callables_2.sendConversationMessage; } });
Object.defineProperty(exports, "markConversationRead", { enumerable: true, get: function () { return callables_2.markConversationRead; } });
Object.defineProperty(exports, "archiveConversation", { enumerable: true, get: function () { return callables_2.archiveConversation; } });
Object.defineProperty(exports, "unarchiveConversation", { enumerable: true, get: function () { return callables_2.unarchiveConversation; } });
Object.defineProperty(exports, "blockConversation", { enumerable: true, get: function () { return callables_2.blockConversation; } });
Object.defineProperty(exports, "unblockConversation", { enumerable: true, get: function () { return callables_2.unblockConversation; } });
Object.defineProperty(exports, "deleteConversation", { enumerable: true, get: function () { return callables_2.deleteConversation; } });
Object.defineProperty(exports, "deleteConversationMessage", { enumerable: true, get: function () { return callables_2.deleteConversationMessage; } });
var callables_3 = require("./modules/notifications/callables");
Object.defineProperty(exports, "registerPushToken", { enumerable: true, get: function () { return callables_3.registerPushToken; } });
Object.defineProperty(exports, "unregisterPushToken", { enumerable: true, get: function () { return callables_3.unregisterPushToken; } });
var triggers_6 = require("./modules/notifications/triggers");
Object.defineProperty(exports, "onNotificationCreated", { enumerable: true, get: function () { return triggers_6.onNotificationCreated; } });
Object.defineProperty(exports, "onNotificationUpdated", { enumerable: true, get: function () { return triggers_6.onNotificationUpdated; } });
var triggers_7 = require("./modules/support/triggers");
Object.defineProperty(exports, "onSupportTicketCreated", { enumerable: true, get: function () { return triggers_7.onSupportTicketCreated; } });
Object.defineProperty(exports, "onSupportTicketReplied", { enumerable: true, get: function () { return triggers_7.onSupportTicketReplied; } });
var triggers_8 = require("./modules/moderation/triggers");
Object.defineProperty(exports, "onReportCreated", { enumerable: true, get: function () { return triggers_8.onReportCreated; } });
Object.defineProperty(exports, "onReportUpdated", { enumerable: true, get: function () { return triggers_8.onReportUpdated; } });
var triggers_9 = require("./modules/billing/triggers");
Object.defineProperty(exports, "onSubscriptionUpdated", { enumerable: true, get: function () { return triggers_9.onSubscriptionUpdated; } });
Object.defineProperty(exports, "onBillingInvoiceUpdated", { enumerable: true, get: function () { return triggers_9.onBillingInvoiceUpdated; } });
var triggers_10 = require("./modules/email/queue/triggers");
Object.defineProperty(exports, "enqueueEmailJobsFromEventTrigger", { enumerable: true, get: function () { return triggers_10.enqueueEmailJobsFromEventTrigger; } });
Object.defineProperty(exports, "processEmailJobTrigger", { enumerable: true, get: function () { return triggers_10.processEmailJobTrigger; } });
Object.defineProperty(exports, "processScheduledEmailDigests", { enumerable: true, get: function () { return triggers_10.processScheduledEmailDigests; } });
Object.defineProperty(exports, "retryFailedEmailJobs", { enumerable: true, get: function () { return triggers_10.retryFailedEmailJobs; } });
Object.defineProperty(exports, "cleanupExpiredEmailJobs", { enumerable: true, get: function () { return triggers_10.cleanupExpiredEmailJobs; } });
var handler_1 = require("./modules/email/webhooks/handler");
Object.defineProperty(exports, "handleEmailProviderWebhook", { enumerable: true, get: function () { return handler_1.handleEmailProviderWebhook; } });
var scheduled_4 = require("./modules/email/scheduled");
Object.defineProperty(exports, "purgeOldEmailWebhooks", { enumerable: true, get: function () { return scheduled_4.purgeOldEmailWebhooks; } });
Object.defineProperty(exports, "purgeOldEmailLogs", { enumerable: true, get: function () { return scheduled_4.purgeOldEmailLogs; } });
Object.defineProperty(exports, "syncEmailAnalytics", { enumerable: true, get: function () { return scheduled_4.syncEmailAnalytics; } });
//# sourceMappingURL=index.js.map