"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.syncEmailAnalytics = exports.purgeOldEmailLogs = exports.purgeOldEmailWebhooks = exports.handleEmailProviderWebhook = exports.cleanupExpiredEmailJobs = exports.retryFailedEmailJobs = exports.processScheduledEmailDigests = exports.processEmailJobTrigger = exports.enqueueEmailJobsFromEventTrigger = exports.onBillingInvoiceUpdated = exports.onSubscriptionUpdated = exports.onReportUpdated = exports.onReportCreated = exports.onSupportTicketReplied = exports.onSupportTicketCreated = exports.markConversationRead = exports.sendConversationMessage = exports.ensureOfferConversation = exports.enqueueUnreadMessageReminders = exports.onConversationSubMessageCreated = exports.onMessageCreated = exports.onNewsletterCampaignUpdated = exports.onNewsletterCampaignCreated = exports.enqueueMarketingOnboardingEmails = exports.onLegalPrivacySettingsUpdated = exports.onLegalTermsSettingsUpdated = exports.enqueueExpiringListingEmails = exports.onOfferUpdated = exports.onOfferCreated = exports.onListingPublished = exports.trackUserLogin = exports.reportPasswordChanged = exports.requestEmailVerificationEmail = exports.requestPasswordResetEmail = exports.onUserCreated = void 0;
const v2_1 = require("firebase-functions/v2");
const env_1 = require("./config/env");
(0, v2_1.setGlobalOptions)({
    secrets: env_1.EMAIL_PROVIDER_SECRETS,
});
var triggers_1 = require("./modules/auth/triggers");
Object.defineProperty(exports, "onUserCreated", { enumerable: true, get: function () { return triggers_1.onUserCreated; } });
var callables_1 = require("./modules/auth/callables");
Object.defineProperty(exports, "requestPasswordResetEmail", { enumerable: true, get: function () { return callables_1.requestPasswordResetEmail; } });
Object.defineProperty(exports, "requestEmailVerificationEmail", { enumerable: true, get: function () { return callables_1.requestEmailVerificationEmail; } });
Object.defineProperty(exports, "reportPasswordChanged", { enumerable: true, get: function () { return callables_1.reportPasswordChanged; } });
Object.defineProperty(exports, "trackUserLogin", { enumerable: true, get: function () { return callables_1.trackUserLogin; } });
var triggers_2 = require("./modules/listings/triggers");
Object.defineProperty(exports, "onListingPublished", { enumerable: true, get: function () { return triggers_2.onListingPublished; } });
Object.defineProperty(exports, "onOfferCreated", { enumerable: true, get: function () { return triggers_2.onOfferCreated; } });
Object.defineProperty(exports, "onOfferUpdated", { enumerable: true, get: function () { return triggers_2.onOfferUpdated; } });
var scheduled_1 = require("./modules/listings/scheduled");
Object.defineProperty(exports, "enqueueExpiringListingEmails", { enumerable: true, get: function () { return scheduled_1.enqueueExpiringListingEmails; } });
var triggers_3 = require("./modules/legal/triggers");
Object.defineProperty(exports, "onLegalTermsSettingsUpdated", { enumerable: true, get: function () { return triggers_3.onLegalTermsSettingsUpdated; } });
Object.defineProperty(exports, "onLegalPrivacySettingsUpdated", { enumerable: true, get: function () { return triggers_3.onLegalPrivacySettingsUpdated; } });
var scheduled_2 = require("./modules/marketing/scheduled");
Object.defineProperty(exports, "enqueueMarketingOnboardingEmails", { enumerable: true, get: function () { return scheduled_2.enqueueMarketingOnboardingEmails; } });
var triggers_4 = require("./modules/marketing/triggers");
Object.defineProperty(exports, "onNewsletterCampaignCreated", { enumerable: true, get: function () { return triggers_4.onNewsletterCampaignCreated; } });
Object.defineProperty(exports, "onNewsletterCampaignUpdated", { enumerable: true, get: function () { return triggers_4.onNewsletterCampaignUpdated; } });
var triggers_5 = require("./modules/messaging/triggers");
Object.defineProperty(exports, "onMessageCreated", { enumerable: true, get: function () { return triggers_5.onMessageCreated; } });
Object.defineProperty(exports, "onConversationSubMessageCreated", { enumerable: true, get: function () { return triggers_5.onConversationSubMessageCreated; } });
var scheduled_3 = require("./modules/messaging/scheduled");
Object.defineProperty(exports, "enqueueUnreadMessageReminders", { enumerable: true, get: function () { return scheduled_3.enqueueUnreadMessageReminders; } });
var callables_2 = require("./modules/messaging/callables");
Object.defineProperty(exports, "ensureOfferConversation", { enumerable: true, get: function () { return callables_2.ensureOfferConversation; } });
Object.defineProperty(exports, "sendConversationMessage", { enumerable: true, get: function () { return callables_2.sendConversationMessage; } });
Object.defineProperty(exports, "markConversationRead", { enumerable: true, get: function () { return callables_2.markConversationRead; } });
var triggers_6 = require("./modules/support/triggers");
Object.defineProperty(exports, "onSupportTicketCreated", { enumerable: true, get: function () { return triggers_6.onSupportTicketCreated; } });
Object.defineProperty(exports, "onSupportTicketReplied", { enumerable: true, get: function () { return triggers_6.onSupportTicketReplied; } });
var triggers_7 = require("./modules/moderation/triggers");
Object.defineProperty(exports, "onReportCreated", { enumerable: true, get: function () { return triggers_7.onReportCreated; } });
Object.defineProperty(exports, "onReportUpdated", { enumerable: true, get: function () { return triggers_7.onReportUpdated; } });
var triggers_8 = require("./modules/billing/triggers");
Object.defineProperty(exports, "onSubscriptionUpdated", { enumerable: true, get: function () { return triggers_8.onSubscriptionUpdated; } });
Object.defineProperty(exports, "onBillingInvoiceUpdated", { enumerable: true, get: function () { return triggers_8.onBillingInvoiceUpdated; } });
var triggers_9 = require("./modules/email/queue/triggers");
Object.defineProperty(exports, "enqueueEmailJobsFromEventTrigger", { enumerable: true, get: function () { return triggers_9.enqueueEmailJobsFromEventTrigger; } });
Object.defineProperty(exports, "processEmailJobTrigger", { enumerable: true, get: function () { return triggers_9.processEmailJobTrigger; } });
Object.defineProperty(exports, "processScheduledEmailDigests", { enumerable: true, get: function () { return triggers_9.processScheduledEmailDigests; } });
Object.defineProperty(exports, "retryFailedEmailJobs", { enumerable: true, get: function () { return triggers_9.retryFailedEmailJobs; } });
Object.defineProperty(exports, "cleanupExpiredEmailJobs", { enumerable: true, get: function () { return triggers_9.cleanupExpiredEmailJobs; } });
var handler_1 = require("./modules/email/webhooks/handler");
Object.defineProperty(exports, "handleEmailProviderWebhook", { enumerable: true, get: function () { return handler_1.handleEmailProviderWebhook; } });
var scheduled_4 = require("./modules/email/scheduled");
Object.defineProperty(exports, "purgeOldEmailWebhooks", { enumerable: true, get: function () { return scheduled_4.purgeOldEmailWebhooks; } });
Object.defineProperty(exports, "purgeOldEmailLogs", { enumerable: true, get: function () { return scheduled_4.purgeOldEmailLogs; } });
Object.defineProperty(exports, "syncEmailAnalytics", { enumerable: true, get: function () { return scheduled_4.syncEmailAnalytics; } });
//# sourceMappingURL=index.js.map